language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2

os:
  - linux
  - osx

cache: bundler

branches:
  only:
    - master

gemfile:
  - Gemfile

script: bundle exec rake

sudo: false

